version: '3.7'

services:
  app:
    image: "djangomyproject"
    command: "python manage.py runserver 0:8000"
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - "./:/app/shared/"